# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1296, 702)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAcceptDrops(False)
        self.centralwidget.setStyleSheet("#on_offFrame{\n"
"    border:2px solid #EF1B79;\n"
"}\n"
"#leftGrid{\n"
"    background-color: rgb(0, 170, 127);\n"
"}\n"
"#systemSetting_Frame{\n"
"    border: 1px solid #2F2D2D;\n"
"}\n"
"#rejectionSetting_Frame{\n"
"    border: 1px solid #2F2D2D;\n"
"}\n"
"#cameraSetting_Frame{\n"
"    border: 1px solid #2F2D2D;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.mainWindowGrid = QtWidgets.QGridLayout(self.centralwidget)
        self.mainWindowGrid.setContentsMargins(0, 0, 0, 0)
        self.mainWindowGrid.setVerticalSpacing(6)
        self.mainWindowGrid.setObjectName("mainWindowGrid")
        self.rightGrid = QtWidgets.QWidget(self.centralwidget)
        self.rightGrid.setMinimumSize(QtCore.QSize(250, 500))
        self.rightGrid.setMaximumSize(QtCore.QSize(1200, 16777215))
        self.rightGrid.setStyleSheet("background-color: rgb(0, 170, 127);")
        self.rightGrid.setObjectName("rightGrid")
        self.mainWindowGrid.addWidget(self.rightGrid, 2, 2, 1, 1)
        self.leftGrid = QtWidgets.QWidget(self.centralwidget)
        self.leftGrid.setMinimumSize(QtCore.QSize(250, 500))
        self.leftGrid.setMaximumSize(QtCore.QSize(250, 16777215))
        self.leftGrid.setAutoFillBackground(False)
        self.leftGrid.setObjectName("leftGrid")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.leftGrid)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.create_project_button = QtWidgets.QPushButton(self.leftGrid)
        self.create_project_button.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.create_project_button.setFont(font)
        self.create_project_button.setObjectName("create_project_button")
        self.verticalLayout_4.addWidget(self.create_project_button)
        self.camera_button = QtWidgets.QPushButton(self.leftGrid)
        self.camera_button.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.camera_button.setFont(font)
        self.camera_button.setObjectName("camera_button")
        self.verticalLayout_4.addWidget(self.camera_button)
        self.data_augment_button = QtWidgets.QPushButton(self.leftGrid)
        self.data_augment_button.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.data_augment_button.setFont(font)
        self.data_augment_button.setObjectName("data_augment_button")
        self.verticalLayout_4.addWidget(self.data_augment_button)
        self.detection_button = QtWidgets.QPushButton(self.leftGrid)
        self.detection_button.setMaximumSize(QtCore.QSize(300, 70))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.detection_button.setFont(font)
        self.detection_button.setObjectName("detection_button")
        self.verticalLayout_4.addWidget(self.detection_button)
        self.mainWindowGrid.addWidget(self.leftGrid, 2, 0, 1, 1)
        self.topGrid = QtWidgets.QWidget(self.centralwidget)
        self.topGrid.setMinimumSize(QtCore.QSize(0, 0))
        self.topGrid.setMaximumSize(QtCore.QSize(16777215, 90))
        self.topGrid.setMouseTracking(True)
        self.topGrid.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"on_offFrame:{\n"
"    border: 2px solid red;\n"
"}")
        self.topGrid.setObjectName("topGrid")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.topGrid)
        self.horizontalLayout.setContentsMargins(66, -1, -1, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 0, -1, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cameraStatus = QtWidgets.QLabel(self.topGrid)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.cameraStatus.setFont(font)
        self.cameraStatus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cameraStatus.setAutoFillBackground(False)
        self.cameraStatus.setAlignment(QtCore.Qt.AlignCenter)
        self.cameraStatus.setObjectName("cameraStatus")
        self.verticalLayout.addWidget(self.cameraStatus)
        self.on_offFrame = QtWidgets.QFrame(self.topGrid)
        self.on_offFrame.setMaximumSize(QtCore.QSize(195, 170))
        self.on_offFrame.setStyleSheet("border-color:#EF1B79;")
        self.on_offFrame.setFrameShape(QtWidgets.QFrame.Panel)
        self.on_offFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.on_offFrame.setLineWidth(2)
        self.on_offFrame.setObjectName("on_offFrame")
        self.gridLayout = QtWidgets.QGridLayout(self.on_offFrame)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.onButton = QtWidgets.QPushButton(self.on_offFrame)
        self.onButton.setMinimumSize(QtCore.QSize(0, 0))
        self.onButton.setMaximumSize(QtCore.QSize(89, 57))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.onButton.setFont(font)
        self.onButton.setStyleSheet("QPushButton{\n"
"    background-color: white;\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-top:2px solid black;\n"
"    border-left: 2px solid black;\n"
"}\n"
"")
        self.onButton.setAutoDefault(False)
        self.onButton.setFlat(False)
        self.onButton.setObjectName("onButton")
        self.gridLayout_2.addWidget(self.onButton, 0, 0, 1, 1)
        self.offButton = QtWidgets.QPushButton(self.on_offFrame)
        self.offButton.setMaximumSize(QtCore.QSize(140, 47))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.offButton.setFont(font)
        self.offButton.setStyleSheet("QPushButton{\n"
"    background: #EF1B79;\n"
"    color:white;\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-left:2px solid black;\n"
"    border-top:2px solid black;\n"
"}\n"
"    \n"
"")
        self.offButton.setAutoDefault(False)
        self.offButton.setDefault(False)
        self.offButton.setFlat(False)
        self.offButton.setObjectName("offButton")
        self.gridLayout_2.addWidget(self.offButton, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.on_offFrame)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.switchMode = QtWidgets.QLabel(self.topGrid)
        self.switchMode.setMaximumSize(QtCore.QSize(16777215, 12))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.switchMode.setFont(font)
        self.switchMode.setAlignment(QtCore.Qt.AlignCenter)
        self.switchMode.setObjectName("switchMode")
        self.verticalLayout_2.addWidget(self.switchMode)
        self.switchButton = QtWidgets.QPushButton(self.topGrid)
        self.switchButton.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.switchButton.setFont(font)
        self.switchButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(238, 237, 237);\n"
"    border:none;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(238, 237, 237);\n"
"    border-left:2px solid rgb(100,180,180);\n"
"    border-top:2px solid rgb(100,180,180);\n"
"}")
        self.switchButton.setAutoDefault(True)
        self.switchButton.setFlat(False)
        self.switchButton.setObjectName("switchButton")
        self.verticalLayout_2.addWidget(self.switchButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, 21)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.activeProject = QtWidgets.QLabel(self.topGrid)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.activeProject.setFont(font)
        self.activeProject.setAlignment(QtCore.Qt.AlignCenter)
        self.activeProject.setObjectName("activeProject")
        self.verticalLayout_3.addWidget(self.activeProject)
        self.label = QtWidgets.QLabel(self.topGrid)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        spacerItem = QtWidgets.QSpacerItem(558, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.crimsonLogo = QtWidgets.QLabel(self.topGrid)
        self.crimsonLogo.setMaximumSize(QtCore.QSize(176, 52))
        self.crimsonLogo.setText("")
        self.crimsonLogo.setPixmap(QtGui.QPixmap("LOGO/main logo.png"))
        self.crimsonLogo.setScaledContents(True)
        self.crimsonLogo.setObjectName("crimsonLogo")
        self.horizontalLayout.addWidget(self.crimsonLogo)
        self.mainWindowGrid.addWidget(self.topGrid, 0, 0, 1, 3)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.create_project_button.setText(_translate("MainWindow", "Create Project"))
        self.camera_button.setText(_translate("MainWindow", "Camera"))
        self.data_augment_button.setText(_translate("MainWindow", "Data Augmentation"))
        self.detection_button.setText(_translate("MainWindow", "Detection"))
        self.cameraStatus.setText(_translate("MainWindow", "Camera Status"))
        self.onButton.setText(_translate("MainWindow", "ON"))
        self.offButton.setText(_translate("MainWindow", "OFF"))
        self.switchMode.setText(_translate("MainWindow", "Switch Mode"))
        self.switchButton.setText(_translate("MainWindow", "Debug"))
        self.activeProject.setText(_translate("MainWindow", "Active Project"))
        self.label.setText(_translate("MainWindow", "EXAMPLE"))
        # self.create_project_label.setText(_translate("MainWindow", "Step 1: Create New Project "))
        # self.create_button.setText(_translate("MainWindow", "Create"))
        # self.import_button.setText(_translate("MainWindow", "Import"))


if __name__ == "__main__":
    import sys
    # Enable high DPI scaling
    if hasattr(QtCore.Qt, 'AA_EnableHighDpiScaling'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_EnableHighDpiScaling, True)

    if hasattr(QtCore.Qt, 'AA_UseHighDpiPixmaps'):
        QtWidgets.QApplication.setAttribute(QtCore.Qt.AA_UseHighDpiPixmaps, True)
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
