brand_name: test
brand_path: ./Brands\test\
detection_dataset_path: ./Brands\test\detection\dataset\
detection_model_path: ./Brands\test\detection\model\
detection_path: ./Brands\test\detection\
detection_result_path: ./Brands\test\detection\result\
good_image_path: ./Brands\test\good_images
images_path: ./Brands\test\images\
main_path: ./Brands
not_good_image_path: ./Brands\test\not_good_images
pickle_path: ./Brands\test\pickle_values
recognition_dataset_path: ./Brands\test\recognition\dataset\
recognition_model_path: ./Brands\test\recognition\model\
recognition_path: ./Brands\test\recognition\
recognition_result_path: ./Brands\test\recognition\result\
