brand_name: batch_code
brand_path: ./Brands\batch_code\
detection_dataset_path: ./Brands\batch_code\detection\dataset\
detection_model_path: ./Brands\batch_code\detection\model\
detection_path: ./Brands\batch_code\detection\
detection_result_path: ./Brands\batch_code\detection\result\
good_image_path: ./Brands\batch_code\good_images
images_path: ./Brands\batch_code\images\
main_path: ./Brands
not_good_image_path: ./Brands\batch_code\not_good_images
pickle_path: ./Brands\batch_code\pickle_values
recognition_dataset_path: ./Brands\batch_code\recognition\dataset\
recognition_model_path: ./Brands\batch_code\recognition\model\
recognition_path: ./Brands\batch_code\recognition\
recognition_result_path: ./Brands\batch_code\recognition\result\
