brand_name: roshan
brand_path: ./Brands\roshan\
detection_dataset_path: ./Brands\roshan\detection\dataset\
detection_model_path: ./Brands\roshan\detection\model\
detection_path: ./Brands\roshan\detection\
detection_result_path: ./Brands\roshan\detection\result\
good_image_path: ./Brands\roshan\good_images
images_path: ./Brands\roshan\images\
main_path: ./Brands
not_good_image_path: ./Brands\roshan\not_good_images
pickle_path: ./Brands\roshan\pickle_values
recognition_dataset_path: ./Brands\roshan\recognition\dataset\
recognition_model_path: ./Brands\roshan\recognition\model\
recognition_path: ./Brands\roshan\recognition\
recognition_result_path: ./Brands\roshan\recognition\result\
