brand_name: sumit
brand_path: ./Brands\sumit\
detection_dataset_path: ./Brands\sumit\detection\dataset\
detection_model_path: ./Brands\sumit\detection\model\
detection_path: ./Brands\sumit\detection\
detection_result_path: ./Brands\sumit\detection\result\
good_image_path: ./Brands\sumit\good_images
images_path: ./Brands\sumit\images\
main_path: ./Brands
not_good_image_path: ./Brands\sumit\not_good_images
pickle_path: ./Brands\sumit\pickle_values
recognition_dataset_path: ./Brands\sumit\recognition\dataset\
recognition_model_path: ./Brands\sumit\recognition\model\
recognition_path: ./Brands\sumit\recognition\
recognition_result_path: ./Brands\sumit\recognition\result\
