brand_name: hero
brand_path: ./Brands\hero\
detection_dataset_path: ./Brands\hero\detection\dataset\
detection_model_path: ./Brands\hero\detection\model\
detection_path: ./Brands\hero\detection\
detection_result_path: ./Brands\hero\detection\result\
good_image_path: ./Brands\hero\good_images
images_path: ./Brands\hero\images\
main_path: ./Brands
not_good_image_path: ./Brands\hero\not_good_images
pickle_path: ./Brands\hero\pickle_values
recognition_dataset_path: ./Brands\hero\recognition\dataset\
recognition_model_path: ./Brands\hero\recognition\model\
recognition_path: ./Brands\hero\recognition\
recognition_result_path: ./Brands\hero\recognition\result\
