from gui.pyUIdesign import Ui_MainWindow
#from gui.PyUICBasicDemo import Ui_MainWindow 
from camera_interface.camera import MachineVisionCamera
from .gui_operations import PyQTWidgetFunction

class Controller():
    """
    Controller class that inherits the Ui_MainWindow from the autogenerated pyqt ui file
    
    :param main_window: instace of the current main window
    :param camera: instance of the MachineVisionCamera    
    """
    def __init__(self, camera: MachineVisionCamera, gui: PyQTWidgetFunction) -> None:
        self.camera = camera
        self.gui = gui

        self.connect_camera_and_ui()
        self.connect_methods_and_ui()


    def connect_camera_and_ui(self):
        ######################## camera function called ##############################
        self.gui.findCamera_Button.clicked.connect(lambda : self.camera.enum_devices(self.gui.comboBox))
        self.gui.onButton.clicked.connect(
            lambda : [self.camera.open_device(self.gui.comboBox), self.camera.start_grabbing(self.gui.imageWidget_Live)] 
        )
        self.gui.offButton.clicked.connect(self.camera.close_device)
        

    def connect_methods_and_ui(self):
        ####################### Live Mode function called ############################
        self.gui.stackWidget.setCurrentWidget(self.gui.liveMode_Page) ####### default switch mode 
        self.gui.editProject.setCurrentWidget(self.gui.createProject_Page) ####### default live mode page
        self.gui.switch_mode_flag = False  ##### switch mode flag
        self.gui.switchButton.clicked.connect(self.gui.switch_mode)
        self.gui.stackWidget_cameraSetting.setCurrentWidget(self.gui.cameraSetting_Page) ######### default camera setting mode
        self.gui.cameraSetting_Button.pressed.connect(self.gui.camera_setting)
        self.gui.openImage_Button.pressed.connect(self.gui.open_image)
        self.gui.saveData_Button.pressed.connect(self.gui.save_data)
        self.gui.click_Button.pressed.connect(self.gui.choose_directory_path)
        self.gui.systemSetting_update_Button.pressed.connect(self.gui.get_live_gui_values)
        self.gui.rejectSetting_updateButton.pressed.connect(self.gui.get_live_gui_values)
        self.gui.cameraSetting_update_Button.pressed.connect(self.gui.get_live_gui_values)
    
        ####################### Debug Mode function called ######################
        self.gui.createProjectButton.clicked.connect(self.gui.create_project)
        self.gui.cameraButton.clicked.connect(self.gui.camera_debug)
        self.gui.preprocessingButton.clicked.connect(self.gui.preprocessing_step)
        self.gui.detectionButton.clicked.connect(self.gui.detection)
        self.gui.recognitionButton.clicked.connect(self.gui.recognition)
        self.gui.analysisButton.clicked.connect(self.gui.analysis)